### ISSUE TITLE
【提问】过拟合问题

### ISSUE THREAD

**Issue by lightyisu** [lhy0322/BertSNR#1]
老师好，对于BertSNR这个模型我非常喜欢。我觉得序列标注引入DNA语言一直是个很棒的想法。但是有些问题比较困惑我，
      我是做元件相关的实验，也是在序列标注的任务进行实验，不过用的基础模型是HyenaDNA,但是在实验中我发现所有的模型不论是最简单的softmax还是crf等解码都会造成整体模型在很少的轮数的验证集上就会产生过拟合。在我的所有模型上超过5轮后基本验证集就会从下降到急剧上升，这让我感到非常地不解，如果是DNA的原因我想不太明白，但是感觉又像是大模型的原因造成的。想请问BertSNR是否也会在很短的轮数就会产生过拟合的效果？
      在我复现了一下BertSNR的训练过程后，您设置的10轮一般在4-5轮似乎就会因为早停自动结束训练，因为我目前还不是很了解多任务的Loss就没有对测试集loss进行计算。如果以我的拙见也出现了过拟合的话，但好像自然语言里似乎就不会产生这样的问题。想请问老师像DNA做这种方向少轮数是正常的吗？
     如果老师有空帮我解答，我表示非常感谢！

**Comment by lhy0322** [comment]
您好！非常高兴我的工作能够帮助到您。您提到的过拟合问题在我做过的诸多DNA序列相关的研究中是非常常见的，如果您的数据量比较少而模型又比较大时（Transformer级别），很容易出现过拟合的情况。使用预训练模型可以稍微缓解这一点（注意是**缓解**），所以，在DNA序列相关任务中少轮数的训练是正常的。在我遇到此类情况时一般有几种方案：
[1]简单设置早停。[2]数据增强，扩充数据集，如滑动窗口（包含您需要元件做上下游随机滑动），整合多个数据库来源数据（以Enhancer为例，可以使用各种Enhancer数据库整合，再加上和Enhancer相关组蛋白修饰peak的区域等等）。[3]使用CNN-based模型。

**Comment by lightyisu** [comment]
好的谢谢您 我明白了~非常感谢老师您的指导！
